package com.helio.domain.engine

import com.helio.domain.engine.SchemaInferenceEngine
import com.helio.domain.model.DataFieldType
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import spray.json._

import scala.io.Source
import scala.util.Random

class SchemaInferenceEngineSpec extends AnyWordSpec with Matchers {

  import DataFieldType._
  import SchemaInferenceEngine._

  // JSON tests

  "SchemaInferenceEngine.fromJson" should {

    "infer fields from a root JsObject with mixed types" in {
      val json = """{"id": 1, "name": "Alice", "active": true}""".parseJson
      val schema = fromJson(json)
      val fields = schema.fields.map(f => f.name -> f.dataType).toMap
      fields("id")     shouldBe IntegerType
      fields("name")   shouldBe StringType
      fields("active") shouldBe BooleanType
      schema.fields.forall(!_.nullable) shouldBe true
    }

    "infer union of keys from a root JsArray" in {
      val json = """[{"x": 1}, {"x": 2, "y": "hello"}]""".parseJson
      val schema = fromJson(json)
      schema.fields.map(_.name) should contain allOf ("x", "y")
    }

    "return empty schema for non-object/array root" in {
      fromJson(JsString("hello")).fields shouldBe empty
      fromJson(JsNumber(42)).fields      shouldBe empty
    }

    "flatten nested objects with dot notation" in {
      val json = """{"address": {"city": "London", "zip": "EC1"}}""".parseJson
      val schema = fromJson(json)
      schema.fields.map(_.name) should contain allOf ("address.city", "address.zip")
      schema.fields.find(_.name == "address.city").get.dataType shouldBe StringType
    }

    // HEL-599 design.md D4 / final-gate skeptic round 1: a literal dotted key colliding with a
    // path generated by nesting (`{"a.b": 1, "a": {"b": 2}}`) must produce EXACTLY ONE `a.b`
    // field in the inferred schema, not two. `flattenObject` builds its `InferredField` `Seq`
    // directly from `JsonFlattener.leaves` and never folds it into a `Map` itself, so this
    // regresses if `leaves` ever stops deduplicating internally -- asserted here against the
    // real `fromJson(...).fields` output, not a locally re-folded `Map` that could pass even if
    // the shipped schema carried a duplicate.
    "collapses a literal dotted key colliding with a nested path to exactly one field" in {
      val json = """{"a.b": 1, "a": {"b": 2}}""".parseJson
      val schema = fromJson(json)
      schema.fields.count(_.name == "a.b") shouldBe 1
      schema.fields.map(_.name) shouldBe Seq("a.b")
    }

    // Companion to the schema-side assertion above: the row materialised from the SAME colliding
    // input must select the SAME value the schema saw, so schema and rows never disagree even on
    // this pathological edge case (the ticket's core guarantee).
    "agrees with PipelineRowJson.jsRowToRow on which value wins a dotted-key collision" in {
      val json = """{"a.b": 1, "a": {"b": 2}}""".parseJson.asInstanceOf[JsObject]
      val schemaValue = JsonFlattener.leaves(json).toMap.apply("a.b")
      val rowValue     = PipelineRowJson.jsRowToRow(json)("a.b")
      PipelineRowJson.jsValueToAny(schemaValue) shouldBe rowValue
    }

    "mark field nullable when any object has null for that key" in {
      val json = """[{"ts": "2024-01-01"}, {"ts": null}]""".parseJson
      val schema = fromJson(json)
      schema.fields.find(_.name == "ts").get.nullable shouldBe true
    }

    // HEL-868 task 3.1: inverts the old "absence never contributes" assertion. ABSENT encoding --
    // `y` is missing entirely from the second sampled object (no `JsNull`, no key at all) -- and
    // that alone must mark it nullable, per the new composed rule (design D1/D2).
    "mark field nullable when merely absent from some sampled objects (ABSENT encoding)" in {
      val json = """[{"x": 1, "y": "present"}, {"x": 2}]""".parseJson
      val schema = fromJson(json)
      schema.fields.find(_.name == "y").get.nullable shouldBe true
      schema.fields.find(_.name == "x").get.nullable shouldBe false
    }

    // HEL-868 task 3.4: PRESENT-BUT-EMPTY encoding -- `JsString("")` is a present, non-null value
    // in every sampled object, so it must NOT be treated as null (design D3).
    "not mark field nullable when every sampled object supplies an empty string (PRESENT-BUT-EMPTY encoding)" in {
      val json = """[{"note": ""}, {"note": ""}]""".parseJson
      val schema = fromJson(json)
      val field = schema.fields.find(_.name == "note").get
      field.nullable shouldBe false
      field.dataType shouldBe StringType
    }

    // HEL-868 task 3.5: all three encodings side by side in one test, so the distinction is
    // stated in the test itself rather than only across separate files.
    "distinguish all three encodings (absent / explicit null / present-but-empty) in one test" in {
      val absentJson  = """[{"a": 1, "b": 2}, {"a": 3}]""".parseJson
      val nullJson    = """[{"a": 1}, {"a": null}]""".parseJson
      val emptyJson   = """[{"a": ""}, {"a": ""}]""".parseJson

      fromJson(absentJson).fields.find(_.name == "b").get.nullable shouldBe true  // ABSENT
      fromJson(nullJson).fields.find(_.name == "a").get.nullable   shouldBe true  // EXPLICIT NULL
      fromJson(emptyJson).fields.find(_.name == "a").get.nullable  shouldBe false // PRESENT-BUT-EMPTY
    }

    // HEL-868 task 3.6 (AC1, central): a field present in exactly 1 of 100 sampled rows must be
    // inferred nullable -- proven on the produced value, not merely that inference completes.
    "mark a field nullable when it is present in only 1 of 100 sampled rows" in {
      val rows: Vector[JsValue] =
        JsObject("stats" -> JsObject("rec" -> JsNumber(3))) +:
          Vector.fill(99)(JsObject("stats" -> JsObject("other" -> JsNumber(1))))
      val schema = fromJson(JsArray(rows))
      schema.fields.find(_.name == "stats.rec").get.nullable shouldBe true
    }

    // HEL-868 task 3.9: absence must not corrupt the widened TYPE -- a path integral in some
    // objects and absent from the rest still infers IntegerType, never widened to StringType.
    "infer IntegerType (not StringType) for a field that is integral in some rows and absent from the rest" in {
      val rows: Vector[JsValue] = Vector(
        JsObject("v" -> JsNumber(3)),
        JsObject.empty,
        JsObject.empty
      )
      val field = fromJson(JsArray(rows)).fields.find(_.name == "v").get
      field.dataType shouldBe IntegerType
      field.nullable shouldBe true
    }

    // HEL-868 task 3.13 (skeptic design-1 note 3): the same type-independence claim pinned on a
    // second, non-numeric arm -- StringType survives absence too, not just IntegerType.
    "infer StringType (not widened) for a field that is a string in some rows and absent from the rest" in {
      val rows: Vector[JsValue] = Vector(
        JsObject("v" -> JsString("hello")),
        JsObject.empty,
        JsObject.empty
      )
      val field = fromJson(JsArray(rows)).fields.find(_.name == "v").get
      field.dataType shouldBe StringType
      field.nullable shouldBe true
    }

    // HEL-868 task 3.10: a single root JsObject is the only sampled object, so every key it
    // carries with a non-null value stays non-nullable.
    "keep every key non-nullable for a single root JsObject whose values are all non-null" in {
      val json = """{"id": 1, "name": "Alice", "active": true}""".parseJson
      val schema = fromJson(json)
      schema.fields.forall(!_.nullable) shouldBe true
    }

    "infer IntegerType for whole numbers" in {
      val json = """{"count": 42}""".parseJson
      fromJson(json).fields.head.dataType shouldBe IntegerType
    }

    "infer FloatType for numbers with decimal" in {
      val json = """{"ratio": 3.14}""".parseJson
      fromJson(json).fields.head.dataType shouldBe FloatType
    }

    "infer TimestampType from ISO-8601 date string" in {
      val json = """{"created": "2024-01-15"}""".parseJson
      fromJson(json).fields.head.dataType shouldBe TimestampType
    }

    "infer TimestampType from ISO-8601 datetime string" in {
      val json = """{"ts": "2024-01-15T10:30:00Z"}""".parseJson
      fromJson(json).fields.head.dataType shouldBe TimestampType
    }

    "keep StringType for non-timestamp strings" in {
      val json = """{"label": "hello world"}""".parseJson
      fromJson(json).fields.head.dataType shouldBe StringType
    }

    "return empty schema for empty JsArray" in {
      fromJson(JsArray()).fields shouldBe empty
    }
  }

  // HEL-858: recursive merge + type widening across sampled rows.
  "SchemaInferenceEngine.fromJson (HEL-858 recursive merge / widening)" should {

    // [RED] task 3.1 (CENTRAL, AC2): order-independence over a heterogeneous fixture whose
    // elements differ in both nested shape and numeric precision.
    "infer an identical schema regardless of row order (reversed and shuffled)" in {
      val rows: Vector[JsValue] = Vector(
        JsObject("id" -> JsNumber(1), "stats" -> JsObject("a" -> JsNumber(3))),
        JsObject("id" -> JsNumber(2), "stats" -> JsObject("a" -> JsNumber(2.5), "b" -> JsNumber(1))),
        JsObject("id" -> JsNumber(3), "stats" -> JsObject("b" -> JsNumber(4.4), "c" -> JsString("x")))
      )
      val forward = fromJson(JsArray(rows))

      // Content assertion (not merely relative equality): pins what the forward schema actually
      // contains, so this central test cannot be satisfied by a degenerate implementation that
      // returns the same (e.g. empty) schema regardless of input.
      val byName = forward.fields.map(f => f.name -> f.dataType).toMap
      byName shouldBe Map(
        "id"      -> IntegerType,
        "stats.a" -> FloatType,   // widen(3, 2.5) across rows 0 and 1
        "stats.b" -> FloatType,   // widen(1, 4.4) across rows 1 and 2
        "stats.c" -> StringType
      )

      val reversed = fromJson(JsArray(rows.reverse))
      reversed shouldBe forward

      val shuffled = new Random(42).shuffle(rows)
      fromJson(JsArray(shuffled)) shouldBe forward
    }

    // [RED] task 3.2 (AC1): a nested path absent from element 0 but present in a later element
    // still appears in the schema, regardless of position.
    "include a nested path even when the first element lacks it" in {
      val rows: Vector[JsValue] = Vector(
        JsObject("stats" -> JsObject("a" -> JsNumber(1))),
        JsObject("stats" -> JsObject("a" -> JsNumber(2), "rec" -> JsNumber(3)))
      )
      val schema = fromJson(JsArray(rows))
      schema.fields.map(_.name) should contain("stats.rec")
    }

    // [RED] task 3.3 (AC3): widening lattice, order in both directions, mixed-kind fallback,
    // and null-alongside-numeric no longer forcing StringType (design D7).
    "widen types across sampled values per the JSON lattice" in {
      def typeOf(rows: JsValue*): DataFieldType =
        fromJson(JsArray(rows.toVector)).fields.find(_.name == "v").get.dataType
      def nullableOf(rows: JsValue*): Boolean =
        fromJson(JsArray(rows.toVector)).fields.find(_.name == "v").get.nullable

      // integral then fractional -> float
      typeOf(JsObject("v" -> JsNumber(3)), JsObject("v" -> JsNumber(2.5))) shouldBe FloatType
      // fractional then integral -> float
      typeOf(JsObject("v" -> JsNumber(2.5)), JsObject("v" -> JsNumber(3))) shouldBe FloatType
      // number + boolean -> string, NOT boolean
      typeOf(JsObject("v" -> JsNumber(1)), JsObject("v" -> JsBoolean(true))) shouldBe StringType
      // timestamp string + non-timestamp string -> string
      typeOf(JsObject("v" -> JsString("2024-01-15")), JsObject("v" -> JsString("not a date"))) shouldBe StringType
      // null + fractional -> nullable float
      typeOf(JsObject("v" -> JsNull), JsObject("v" -> JsNumber(2.5))) shouldBe FloatType
      nullableOf(JsObject("v" -> JsNull), JsObject("v" -> JsNumber(2.5))) shouldBe true
      // null + integral -> nullable integer (design D7 -- pre-fix a single null forced string)
      typeOf(JsObject("v" -> JsNull), JsObject("v" -> JsNumber(7))) shouldBe IntegerType
      nullableOf(JsObject("v" -> JsNull), JsObject("v" -> JsNumber(7))) shouldBe true
    }

    // [CHAR] task 3.3b: all-null path is still a nullable string, both before and after the fix.
    "infer a nullable StringType for a path that is null in every sampled object" in {
      val rows: Vector[JsValue] = Vector(JsObject("v" -> JsNull), JsObject("v" -> JsNull))
      val field = fromJson(JsArray(rows)).fields.find(_.name == "v").get
      field.dataType shouldBe StringType
      field.nullable shouldBe true
    }

    // [RED] task 3.6 (design D5): a path that is a scalar in one object and a subtree in another
    // yields BOTH paths, and this holds regardless of which row comes first.
    "emit both a scalar path and its subtree path on a cross-row leaf-vs-subtree collision" in {
      val forward  = Vector(JsObject("a" -> JsNumber(1)), JsObject("a" -> JsObject("b" -> JsNumber(2))))
      val backward = forward.reverse

      val forwardSchema  = fromJson(JsArray(forward))
      val backwardSchema = fromJson(JsArray(backward))

      forwardSchema.fields.map(_.name) should contain allOf ("a", "a.b")
      backwardSchema shouldBe forwardSchema
    }

    // [CHAR] task 3.7: within-object collision still yields exactly one `a.b` field -- unchanged
    // since HEL-599, must stay green.
    "still collapse a within-object literal-dotted-key vs nested-path collision to one field" in {
      val json = """{"a.b": 1, "a": {"b": 2}}""".parseJson
      val schema = fromJson(json)
      schema.fields.count(_.name == "a.b") shouldBe 1
      schema.fields.map(_.name) shouldBe Seq("a.b")
    }

    // Design D6's three-sided agreement property, asserted directly on the un-folded `Seq`.
    def assertAgreement(rows: Seq[JsObject]): Unit = {
      val schema = fromJson(JsArray(rows.toVector))
      val schemaNames = schema.fields.map(_.name)
      val rowKeySets  = rows.map(PipelineRowJson.jsRowToRow(_).keySet)

      // (1) every row's key set is a subset of the schema's field-name set
      rowKeySets.foreach { keys =>
        keys.foreach { k => schemaNames should contain(k) }
      }
      // (2) schema field-name set == union of all rows' key sets
      schemaNames.toSet shouldBe rowKeySets.foldLeft(Set.empty[String])(_ ++ _)
      // (3) no duplicates in the schema's field-name Seq itself (never folded into a Set first)
      schemaNames.distinct shouldBe schemaNames
    }

    // [CHAR] task 3.8a: agreement holds pre-fix on these inputs too -- must stay green.
    "hold the three-sided agreement property on inputs where it already held pre-fix" in {
      assertAgreement(Seq(
        JsObject("x" -> JsNumber(1), "y" -> JsString("a")),
        JsObject("x" -> JsNumber(2), "y" -> JsString("b"))
      )) // single-shape rows

      assertAgreement(Seq(JsObject("a.b" -> JsNumber(1)))) // dots inside keys
      assertAgreement(Seq(JsObject("café" -> JsString("x"), "" -> JsString("y")))) // unicode + empty-string keys

      // depth at and beyond JsonFlattener.MaxDepth
      def nest(depth: Int): JsValue =
        if (depth == 0) JsNumber(1) else JsObject("n" -> nest(depth - 1))
      assertAgreement(Seq(JsObject("d" -> nest(JsonFlattener.MaxDepth))))
      assertAgreement(Seq(JsObject("d" -> nest(JsonFlattener.MaxDepth + 5))))

      // non-object array elements alongside real objects
      val mixedArray = JsArray(JsObject("x" -> JsNumber(1)), JsString("not an object"), JsNumber(42))
      val schema = fromJson(mixedArray)
      schema.fields.map(_.name) shouldBe Seq("x")

      assertAgreement(Seq("""{"a.b": 1, "a": {"b": 2}}""".parseJson.asInstanceOf[JsObject])) // within-object collision
    }

    // [RED] task 3.8b: the same three clauses over inputs where the fix is what makes them hold.
    "hold the three-sided agreement property on heterogeneous shapes and cross-row collisions (fix-dependent)" in {
      assertAgreement(Seq(
        JsObject("stats" -> JsObject("a" -> JsNumber(1))),
        JsObject("stats" -> JsObject("a" -> JsNumber(2), "rec" -> JsNumber(3)))
      )) // heterogeneous nested shapes

      assertAgreement(Seq(
        JsObject("a" -> JsNumber(1)),
        JsObject("a" -> JsObject("b" -> JsNumber(2)))
      )) // D5 cross-row leaf-vs-subtree collision
    }

    // [RED] task 3.9 (AC4): the mixed-position Sleeper regression, with in-test fixture adequacy.
    "infer the full stats.rec* family from the live mixed-position Sleeper fixture" in {
      val text = Source.fromResource("hel858/sleeper-mixed-projections-slice.json").mkString
      val rows = text.parseJson.asInstanceOf[JsArray].elements.collect { case o: JsObject => o }

      // Fixture adequacy (design D6): must contain both an earlier element lacking the
      // stats.rec* family and a later element carrying it, or this test proves nothing.
      def hasRecFamily(o: JsObject): Boolean = {
        val stats = o.fields.get("stats").collect { case s: JsObject => s }.getOrElse(JsObject.empty)
        stats.fields.contains("rec") && stats.fields.contains("rec_yd") && stats.fields.contains("rec_td")
      }
      val firstIdxWithout = rows.indexWhere(o => !hasRecFamily(o))
      val laterIdxWith    = rows.indexWhere(hasRecFamily, from = firstIdxWithout + 1)
      withClue("fixture must have an earlier element lacking stats.rec* and a later element carrying it: ") {
        firstIdxWithout should be >= 0
        laterIdxWith should be > firstIdxWithout
      }

      val schema = fromJson(JsArray(rows.toVector))
      schema.fields.map(_.name) should contain allOf ("stats.rec", "stats.rec_yd", "stats.rec_td")
    }

    // HEL-868 task 3.7: the real-fixture proof for AC1 -- `stats.rec` is nullable because QB rows
    // in this fixture lack the whole `stats.rec*` family, and `player_id` (present and non-null
    // in all 15 elements) is the false-positive guard on the same real data.
    "mark stats.rec nullable and player_id non-nullable on the live mixed-position Sleeper fixture" in {
      val text = Source.fromResource("hel858/sleeper-mixed-projections-slice.json").mkString
      val rows = text.parseJson.asInstanceOf[JsArray].elements.collect { case o: JsObject => o }
      val schema = fromJson(JsArray(rows.toVector))

      schema.fields.find(_.name == "stats.rec").get.nullable shouldBe true
      schema.fields.find(_.name == "player_id").get.nullable shouldBe false
    }

    // HEL-868 task 3.8: nullability must not depend on row order -- pins the FULL
    // (name, type, nullable) triple sequence across forward and reversed order.
    "infer identical (name, type, nullable) triples regardless of row order over a heterogeneous array" in {
      val rows: Vector[JsValue] = Vector(
        JsObject("stats" -> JsObject("a" -> JsNumber(1))),
        JsObject("stats" -> JsObject("a" -> JsNumber(2), "rec" -> JsNumber(3))),
        JsObject("stats" -> JsObject("rec" -> JsNull))
      )
      def triples(v: Vector[JsValue]) =
        fromJson(JsArray(v)).fields.map(f => (f.name, f.dataType, f.nullable))

      val forward  = triples(rows)
      val reversed = triples(rows.reverse)
      reversed shouldBe forward
    }

    // [CHAR] task 3.10a: the WR-only fixture's FIELD-NAME set is unaffected by this ticket --
    // this half genuinely holds both pre-fix and post-fix (63 fields, same names, same sorted
    // order; single-shape source, no D5 collision). Kept separate from 3.10b so revert
    // verification (task 3.11) can check one outcome per artifact.
    "characterise the existing WR-only fixture's field-NAME set (unaffected by this ticket)" in {
      val text = Source.fromResource("hel599/sleeper-wr-projections-slice.json").mkString
      val rows = text.parseJson.asInstanceOf[JsArray].elements.collect { case o: JsObject => o }
      val schema = fromJson(JsArray(rows.toVector))

      schema.fields.size shouldBe 63
      schema.fields.map(_.name) should contain allOf ("stats.pts_ppr", "stats.rec", "player.first_name")
    }

    // [RED] task 3.10b: pins the FULL sorted (name, type, nullable) triple for every field on the
    // WR-only fixture, so the comment's "no other field changes" claim is self-enforcing rather
    // than attested -- a future regression on ANY field (not just the four known-changed ones)
    // fails this test, not a manual diff. Necessarily red on revert: 4 of the 63 pinned values are
    // this ticket's own post-fix answers (full comparison recorded in
    // evidence/wr-fixture-characterisation.md). Two fields DO differ from pre-fix -- a real,
    // correctly-attributed behaviour change:
    //
    //   player.injury_body_part, player.injury_status: nullable false -> true.
    //   Element 2 of this fixture carries an explicit JsNull at both nested paths. Pre-fix,
    //   mergeObjects picked element 0's whole `player` subtree first-non-null-wins (design D1's
    //   defect 1), so `withNulls` -- which only ever nulls TOP-LEVEL keys -- never saw the
    //   nested null. Post-fix, inferFromObjects unions leaf paths across every element, so
    //   element 2's null is visible at its own path. This is NOT a D7 narrowing (D7 is a TYPE
    //   change, string -> numeric; here the type, StringType, is unchanged in both directions)
    //   and it is NOT "legitimate widening" in the D3 lattice sense either -- it is the
    //   unchanged D2 nullability rule ("explicit JsNull anywhere -> nullable") reaching a nested
    //   path for the first time, an inseparable consequence of fixing defect 1. Direction is
    //   false -> true, i.e. strictly more accurate, never a silent loss of nullability info.
    //
    //   stats.pts_half_ppr, stats.rec_fd: integer -> float. Legitimate widening across non-null
    //   values sampled from more than the first element -- unrelated to the nullability flip
    //   above, and not a D7 case.
    //
    //   No other field changes name, type, or nullability on this fixture (no numeric column
    //   here is ever null, so D7's narrowing does not trigger on this particular fixture) --
    //   enforced by pinning all 63 fields below, not merely claimed.
    "pin the WR-only fixture's full field-by-field schema (name, type, nullable)" in {
      val text = Source.fromResource("hel599/sleeper-wr-projections-slice.json").mkString
      val rows = text.parseJson.asInstanceOf[JsArray].elements.collect { case o: JsObject => o }
      val schema = fromJson(JsArray(rows.toVector))
      val actual = schema.fields.sortBy(_.name).map(f => (f.name, f.dataType, f.nullable))

      val expected = Seq(
        ("category", StringType, false),
        ("company", StringType, false),
        ("date", StringType, true),
        ("game_id", StringType, false),
        ("last_modified", IntegerType, false),
        ("opponent", StringType, true),
        ("player.fantasy_positions", StringType, false),
        ("player.first_name", StringType, false),
        ("player.injury_body_part", StringType, true),
        ("player.injury_notes", StringType, true),
        ("player.injury_start_date", StringType, true),
        ("player.injury_status", StringType, true),
        ("player.last_name", StringType, false),
        ("player.metadata.channel_id", StringType, false),
        ("player.metadata.genius_id", StringType, false),
        ("player.metadata.rookie_year", StringType, false),
        ("player.news_updated", IntegerType, false),
        ("player.position", StringType, false),
        ("player.team", StringType, false),
        ("player.team_abbr", StringType, true),
        ("player.team_changed_at", StringType, true),
        ("player.years_exp", IntegerType, false),
        ("player_id", StringType, false),
        ("season", StringType, false),
        ("season_type", StringType, false),
        ("sport", StringType, false),
        ("stats.adp_2qb", FloatType, false),
        ("stats.adp_dynasty", IntegerType, false),
        ("stats.adp_dynasty_2qb", FloatType, false),
        ("stats.adp_dynasty_half_ppr", FloatType, false),
        ("stats.adp_dynasty_ppr", FloatType, false),
        ("stats.adp_dynasty_std", FloatType, false),
        ("stats.adp_half_ppr", FloatType, false),
        ("stats.adp_idp", FloatType, false),
        ("stats.adp_idp_1qb", FloatType, false),
        ("stats.adp_ppr", FloatType, false),
        ("stats.adp_rookie", IntegerType, false),
        ("stats.adp_std", FloatType, false),
        ("stats.bonus_rec_wr", IntegerType, false),
        ("stats.fum_lost", IntegerType, false),
        ("stats.gp", IntegerType, false),
        ("stats.pts_half_ppr", FloatType, false),
        ("stats.pts_ppr", FloatType, false),
        ("stats.pts_std", FloatType, false),
        ("stats.rec", IntegerType, false),
        ("stats.rec_0_4", FloatType, false),
        ("stats.rec_10_19", FloatType, false),
        ("stats.rec_20_29", FloatType, false),
        ("stats.rec_2pt", IntegerType, false),
        ("stats.rec_30_39", FloatType, false),
        ("stats.rec_40p", FloatType, false),
        ("stats.rec_5_9", FloatType, false),
        ("stats.rec_fd", FloatType, false),
        ("stats.rec_td", IntegerType, false),
        ("stats.rec_yd", IntegerType, false),
        ("stats.rush_att", IntegerType, false),
        ("stats.rush_fd", FloatType, false),
        ("stats.rush_yd", IntegerType, false),
        ("status", StringType, true),
        ("team", StringType, false),
        ("updated_at", IntegerType, false),
        ("week", StringType, true),
        ("week_shard", StringType, false)
      )

      actual shouldBe expected
    }
  }

  // inferSchemaFromRows (HEL-473 facade)

  "SchemaInferenceEngine.inferSchemaFromRows" should {

    "produce output identical to fromJson(JsArray(rows)) for a Vector of row objects" in {
      val rows = Vector(
        """{"id": 1, "name": "Alice"}""".parseJson,
        """{"id": 2, "name": "Bob", "active": true}""".parseJson
      )
      inferSchemaFromRows(rows) shouldBe fromJson(JsArray(rows))
    }

    "produce output identical to fromJson(JsArray(rows)) for an empty Vector" in {
      inferSchemaFromRows(Vector.empty) shouldBe fromJson(JsArray(Vector.empty))
      inferSchemaFromRows(Vector.empty).fields shouldBe empty
    }

    "produce output identical to fromJson(JsArray(rows)) when rows contain non-object elements" in {
      val rows = Vector(JsString("not an object"), JsNumber(42))
      inferSchemaFromRows(rows) shouldBe fromJson(JsArray(rows))
      inferSchemaFromRows(rows).fields shouldBe empty
    }

    "produce output identical to fromJson(JsArray(rows)) for a single-row Vector (mirrors a JsObject root)" in {
      val rows = Vector("""{"address": {"city": "London", "zip": "EC1"}}""".parseJson)
      inferSchemaFromRows(rows) shouldBe fromJson(JsArray(rows))
      inferSchemaFromRows(rows).fields.map(_.name) should contain allOf ("address.city", "address.zip")
    }

    "derive field names, types, and nullability from arbitrary supplied rows (HEL-473 task 4.4)" in {
      // Mirrors a new connector's `fetch` output funnelled straight into the facade, per
      // ConnectorDriver.scala's '''Schema inference''' doc block.
      val rows: Vector[JsValue] = Vector(
        JsObject("sku" -> JsString("A1"), "qty" -> JsNumber(5), "note" -> JsNull),
        JsObject("sku" -> JsString("A2"), "qty" -> JsNumber(7), "note" -> JsString("low stock"))
      )
      val schema = inferSchemaFromRows(rows)
      val byName = schema.fields.map(f => f.name -> f).toMap

      byName.keySet shouldBe Set("sku", "qty", "note")
      byName("sku").dataType  shouldBe StringType
      byName("sku").nullable  shouldBe false
      byName("qty").dataType  shouldBe IntegerType
      byName("qty").nullable  shouldBe false
      byName("note").dataType shouldBe StringType
      byName("note").nullable shouldBe true
    }
  }

  // CSV tests

  "SchemaInferenceEngine.fromCsv" should {

    "use header row as field names" in {
      val csv = "id,name,score\n1,Alice,9.5"
      fromCsv(csv).fields.map(_.name) shouldBe Seq("id", "name", "score")
    }

    // HEL-893 design D1: every CSV column reports StringType, matching what
    // `InProcessPipelineEngine.loadCsvRowsFromBytes` actually materializes (String, always).
    // These scenario names are unchanged from before HEL-893 so the "what a column of this
    // shape used to widen to" story stays legible; only the asserted type changed.
    "infer StringType (was IntegerType) when all values are whole numbers" in {
      val csv = "count\n1\n2\n3"
      fromCsv(csv).fields.head.dataType shouldBe StringType
    }

    "infer StringType (was FloatType) when column contains a decimal" in {
      val csv = "value\n1\n1.5\n3"
      fromCsv(csv).fields.head.dataType shouldBe StringType
    }

    "infer StringType (was BooleanType) when all values are true/false (case-insensitive)" in {
      val csv = "flag\ntrue\nFalse\nTRUE"
      fromCsv(csv).fields.head.dataType shouldBe StringType
    }

    "infer StringType (was TimestampType) when all values match a date pattern" in {
      val csv = "created\n2024-01-01\n2024-06-15"
      fromCsv(csv).fields.head.dataType shouldBe StringType
    }

    "infer StringType for mixed values" in {
      val csv = "mixed\n1\nhello\n3"
      fromCsv(csv).fields.head.dataType shouldBe StringType
    }

    "mark field nullable when any cell is empty" in {
      val csv = "val\n1\n\n3"
      fromCsv(csv).fields.head.nullable shouldBe true
    }

    "not mark field nullable when no empty cells" in {
      val csv = "val\n1\n2\n3"
      fromCsv(csv).fields.head.nullable shouldBe false
    }

    // HEL-868 task 3.11: pins the JSON/CSV agreement-on-absence claim (design D4) -- a ragged
    // row's missing trailing column already pads to an empty cell and is marked nullable, with
    // no code change to fromCsv required.
    "mark a ragged short row's missing trailing column nullable (agrees with JSON's absence rule)" in {
      val csv = "id,name,score\n1,Alice"
      val schema = fromCsv(csv)
      schema.fields.find(_.name == "score").get.nullable shouldBe true
    }

    "cap sampling at 100 rows" in {
      // Rows 1-100 are integers; row 101 is "hello" — should NOT affect the result
      // (HEL-893: type is StringType regardless, but the 100-row cap on nullability
      // sampling is what this test actually pins -- add a 101st empty cell that must
      // NOT be sampled).
      val dataRows = (1 to 100).map(_.toString) ++ Seq("")
      val csv = "val\n" + dataRows.mkString("\n")
      val schema = fromCsv(csv)
      schema.fields.head.dataType shouldBe StringType
      schema.fields.head.nullable shouldBe false
    }

    "handle a CSV with only a header row" in {
      val csv = "id,name"
      val schema = fromCsv(csv)
      schema.fields.map(_.name) shouldBe Seq("id", "name")
      schema.fields.forall(_.dataType == StringType) shouldBe true
    }

    "return empty schema for empty CSV" in {
      fromCsv("").fields shouldBe empty
    }

    "parse quoted field containing a comma as a single field" in {
      val csv = "name,age\n\"Smith, John\",30"
      val schema = fromCsv(csv)
      schema.fields.map(_.name) shouldBe Seq("name", "age")
      schema.fields.find(_.name == "age").get.dataType shouldBe DataFieldType.StringType
    }

    "unescape double-quotes inside quoted fields" in {
      val csv = "label\n\"say \"\"hello\"\"\""
      val schema = fromCsv(csv)
      schema.fields.head.dataType shouldBe DataFieldType.StringType
    }

    "accept CRLF line endings" in {
      val csv = "id,name\r\n1,Alice\r\n2,Bob"
      val schema = fromCsv(csv)
      schema.fields.map(_.name) shouldBe Seq("id", "name")
      schema.fields.find(_.name == "id").get.dataType shouldBe DataFieldType.StringType
    }
  }

  // displayName tests

  "SchemaInferenceEngine.displayName" should {

    "convert snake_case to title case" in {
      displayName("created_at") shouldBe "Created At"
    }

    "convert camelCase to title case" in {
      displayName("firstName") shouldBe "First Name"
    }

    "convert dot-separated path to title case" in {
      displayName("address.city") shouldBe "Address City"
    }

    "handle single-word names" in {
      displayName("name") shouldBe "Name"
    }

    "handle mixed snake and camel" in {
      displayName("user_firstName") shouldBe "User First Name"
    }
  }

  // DataFieldType.asString

  "DataFieldType.asString" should {

    "return canonical lowercase strings" in {
      DataFieldType.asString(StringType)    shouldBe "string"
      DataFieldType.asString(IntegerType)   shouldBe "integer"
      DataFieldType.asString(FloatType)     shouldBe "float"
      DataFieldType.asString(BooleanType)   shouldBe "boolean"
      DataFieldType.asString(TimestampType) shouldBe "timestamp"
    }
  }
}
