akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
  loglevel = "INFO"
  loglevel = ${?LOG_LEVEL}
  license-key = ""
  license-key = ${?AKKA_LICENSE_KEY}
}

helio.db {
  host = "localhost"
  host = ${?DB_HOST}
  port = 5432
  port = ${?DB_PORT}
  name = "helio"
  name = ${?DB_NAME}

  url = "jdbc:postgresql://"${helio.db.host}":"${helio.db.port}"/"${helio.db.name}
  url = ${?DATABASE_URL}

  user = ""
  user = ${?DB_USER}
  password = ""
  password = ${?DB_PASSWORD}

  driver = "org.postgresql.Driver"
  connectionPool = "HikariCP"
  numThreads = 10
  maxConnections = 10
}
