#!/usr/bin/env bash
set -euo pipefail

# ===========================================================================
# setup-worktree.sh — canonical worktree setup for the ticket-delivery flow.
#
# Deterministic so the orchestrator calls it instead of hand-rolling git
# worktree / env-copy / port math (where hallucination creeps in). Idempotent:
# re-running for an existing worktree reuses it.
#
# Usage:   setup-worktree.sh <TICKET_ID> <BRANCH>
# Example: setup-worktree.sh HEL-55 feature/panel-dup/HEL-55
#
# Reads project config from .concertino.env (next to this script), generated by
# `concertino sync`:
#   CONCERTINO_WORKTREE_BASE     dir (repo-relative) to hold worktrees
#   CONCERTINO_BASE_BRANCH       branch new worktree branches are cut from
#   CONCERTINO_FRONTEND_PORT_BASE / CONCERTINO_BACKEND_PORT_BASE   port bases
#   CONCERTINO_ENV_FILES         space-separated files to copy into the worktree
#   CONCERTINO_LINK_MODULES      space-separated module dirs (e.g.
#                                frontend/node_modules) to populate in the
#                                worktree so pre-commit hooks that need installed
#                                deps can run without `git commit -n`
#   CONCERTINO_WORKTREE_HOOKS    ;-separated commands to run inside the worktree
#
# CONCERTINO_BASE_REMOTE (default: origin) may be set in the environment.
#
# On success prints the stable READY contract (the orchestrator parses these):
#   READY worktree=<absolute path>
#   READY branch=<branch>
#   READY dev_port=<n>
#   READY backend_port=<n>
# Exits non-zero with "FAIL <reason>" on any error.
# ===========================================================================

TICKET_ID="${1:?usage: setup-worktree.sh <TICKET_ID> <BRANCH>}"
BRANCH="${2:?usage: setup-worktree.sh <TICKET_ID> <BRANCH>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
[ -f "${SCRIPT_DIR}/.concertino.env" ] && source "${SCRIPT_DIR}/.concertino.env"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

WORKTREE_BASE="${CONCERTINO_WORKTREE_BASE:-.concertino/worktrees}"
FRONTEND_PORT_BASE="${CONCERTINO_FRONTEND_PORT_BASE:-5173}"
BACKEND_PORT_BASE="${CONCERTINO_BACKEND_PORT_BASE:-8080}"
BASE_REMOTE="${CONCERTINO_BASE_REMOTE:-origin}"
BASE_BRANCH="${CONCERTINO_BASE_BRANCH:-main}"

# Derive stable ports from the ticket number so parallel orchestrators never
# collide. e.g. ticket #55 with default bases -> dev 5228, backend 8135.
TICKET_NUM="${TICKET_ID##*-}"
if ! [[ "$TICKET_NUM" =~ ^[0-9]+$ ]]; then
  echo "FAIL could not derive numeric ticket id from '$TICKET_ID'" >&2
  exit 1
fi
DEV_PORT=$((FRONTEND_PORT_BASE + TICKET_NUM))
BACKEND_PORT=$((BACKEND_PORT_BASE + TICKET_NUM))

WORKTREE_PATH="${REPO_ROOT}/${WORKTREE_BASE}/${BRANCH}"

# Create the worktree (reuse if it already exists for this branch).
if git worktree list --porcelain | grep -qx "worktree ${WORKTREE_PATH}"; then
  echo "note: worktree already present, reusing ${WORKTREE_PATH}" >&2
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "$WORKTREE_PATH" "$BRANCH"      # branch exists, attach
else
  # New branch: cut from the fetched remote base, never from whatever local HEAD
  # happens to be. In a burst of sequential tickets each PR squash-merges on the
  # remote while local <base> stays behind, so branching from HEAD silently
  # produces conflicts whenever two tickets touch the same file.
  # Resuming an existing branch (above) must never re-base — only this path syncs.
  if git fetch --quiet "$BASE_REMOTE" "$BASE_BRANCH" 2>/dev/null &&
    git show-ref --verify --quiet "refs/remotes/${BASE_REMOTE}/${BASE_BRANCH}"; then
    BASE_REF="${BASE_REMOTE}/${BASE_BRANCH}"
  elif git show-ref --verify --quiet "refs/heads/${BASE_BRANCH}"; then
    BASE_REF="$BASE_BRANCH"
    echo "note: could not fetch ${BASE_REMOTE}/${BASE_BRANCH} — cutting from local ${BASE_BRANCH}" >&2
  else
    BASE_REF="HEAD"
    echo "note: no ${BASE_BRANCH} ref found — cutting from HEAD" >&2
  fi
  # --no-track: branching off a remote ref would otherwise set upstream to
  # <remote>/<base>, so `git status` reports the new branch as "ahead of main"
  # and a stray `git pull` would merge base in. Delivery sets the real upstream
  # with `git push -u origin <branch>`.
  git worktree add --no-track "$WORKTREE_PATH" -b "$BRANCH" "$BASE_REF"
fi

# Copy env/secret files the app needs at boot but that aren't committed. Without
# these the dev server (and any login) fails. This is the step prose leaves implicit.
for f in ${CONCERTINO_ENV_FILES:-}; do
  if [ -f "${REPO_ROOT}/${f}" ]; then
    mkdir -p "$(dirname "${WORKTREE_PATH}/${f}")"
    cp -n "${REPO_ROOT}/${f}" "${WORKTREE_PATH}/${f}" 2>/dev/null || true
  else
    echo "note: ${REPO_ROOT}/${f} not found — app may need env set another way" >&2
  fi
done

# Populate configured module directories (e.g. frontend/node_modules) so the
# worktree can run the full pre-commit hook chain — Husky's frontend lint/test
# step needs installed deps, and without this every backend-only ticket resorts
# to `git commit -n`. Runs BEFORE the hooks loop so `npx husky install` (and any
# other hook) sees populated modules.
#
# Best-effort: this script runs under `set -euo pipefail`, so every fallible
# command below (`cmp -s`, `cp -al`, `npm ci`) is guarded to degrade to a
# `note:` and continue — setup MUST still reach the READY lines.
#
# Per module dir M (parent P = dirname M, lockfile P/package-lock.json): prefer a
# HARDLINK COPY (`cp -al`) of the main checkout's modules — near-instant, shared
# inodes, near-zero disk — but the worktree's copy is an independent directory
# entry, so a later `npm ci`/`rm -rf` in the worktree cannot corrupt the main
# checkout. A symlink into the main checkout is intentionally NOT used: `npm ci`
# in the worktree would recurse the link and wipe the shared main modules. Fall
# back to `npm ci` when the lockfile differs, the main modules are missing, or
# the hardlink copy fails (e.g. EXDEV — worktree on a different filesystem).
for M in ${CONCERTINO_LINK_MODULES:-}; do
  [ -z "$M" ] && continue
  P="$(dirname "$M")"
  MAIN_M="${REPO_ROOT}/${M}"
  WT_M="${WORKTREE_PATH}/${M}"
  MAIN_LOCK="${REPO_ROOT}/${P}/package-lock.json"
  WT_LOCK="${WORKTREE_PATH}/${P}/package-lock.json"

  # Idempotent: skip if the worktree already has it (real dir or existing link).
  if [ -e "$WT_M" ] || [ -L "$WT_M" ]; then
    echo "note: ${M} already present in worktree — skipping populate" >&2
    continue
  fi

  did_hardlink=0
  if [ -d "$MAIN_M" ] && [ -f "$MAIN_LOCK" ] && [ -f "$WT_LOCK" ] && cmp -s "$MAIN_LOCK" "$WT_LOCK"; then
    # Unchanged deps → hardlink copy of the main modules.
    if cp -al "$MAIN_M" "$WT_M" 2>/dev/null; then
      did_hardlink=1
    else
      echo "note: hardlink copy of ${M} failed (cross-filesystem?) — falling back to npm ci" >&2
    fi
  fi

  if [ "$did_hardlink" -eq 0 ]; then
    # Lockfile drift, missing/absent main modules, or a failed hardlink copy →
    # real install so the worktree gets its own correct modules.
    if [ -f "$WT_LOCK" ]; then
      ( cd "${WORKTREE_PATH}/${P}" && npm ci >/dev/null 2>&1 ) \
        || echo "note: 'npm ci' for ${M} failed — worktree may need a manual install" >&2
    else
      echo "note: no ${P}/package-lock.json and no reusable main ${M} — leaving ${M} unpopulated" >&2
    fi
  fi
done

# Run project-defined worktree hooks (e.g. `npx husky install`, `npm ci`).
if [ -n "${CONCERTINO_WORKTREE_HOOKS:-}" ]; then
  IFS=';' read -ra HOOKS <<< "$CONCERTINO_WORKTREE_HOOKS"
  for hook in "${HOOKS[@]}"; do
    hook="$(echo "$hook" | sed 's/^ *//;s/ *$//')"
    [ -z "$hook" ] && continue
    ( cd "$WORKTREE_PATH" && eval "$hook" >/dev/null 2>&1 ) || true
  done
fi

echo "READY worktree=${WORKTREE_PATH}"
echo "READY branch=${BRANCH}"
echo "READY dev_port=${DEV_PORT}"
echo "READY backend_port=${BACKEND_PORT}"
