#!/usr/bin/env bash
set -euo pipefail

# ===========================================================================
# setup-worktree.sh — canonical worktree setup for the ticket-delivery flow.
#
# Deterministic so the orchestrator calls it instead of hand-rolling git
# worktree / env-copy / port math (where hallucination creeps in). Idempotent:
# re-running for an existing worktree reuses it.
#
# Usage:   setup-worktree.sh <TICKET_ID> <BRANCH> [SPEED] [HARNESS_OVERRIDE]
# Example: setup-worktree.sh HEL-55 feature/panel-dup/HEL-55 fast
#
#   SPEED            optional; fast|default|slow (defaults to "default" when
#                     omitted, exactly like resolve-speed.sh itself does).
#                     Resolved here — once, this is the run's only resolution
#                     of it — via
#                     `scripts/concertino/resolve-speed.sh "$SPEED" "$MODEL_TIER_HARNESS"`,
#                     passing the harness this script already computed below
#                     rather than re-detecting it a second time. The
#                     resulting budgets/models/flags are folded into this
#                     script's own run.start emission and READY contract (see
#                     both below) — this is the actual, ground-truth
#                     run.start emission site (delivery-speed-presets
#                     design.md Decision 3a), so a run's resolved rigour is
#                     recorded truthfully in the same event that already
#                     defines the run's identity.
#   HARNESS_OVERRIDE  optional (CON-62); a ticket-declared harness
#                     (`claude-code`|`codex`) that takes precedence over both
#                     runtime detection and the static default for the
#                     IDENTITY/telemetry `HARNESS` value only — see the
#                     HARNESS vs MODEL_TIER_HARNESS split below. Validated
#                     against CONCERTINO_IMPLEMENTED_HARNESSES before any
#                     git/worktree operation; an unsupported value FAILs.
#
# Reads project config from .concertino.env (next to this script), generated by
# `concertino sync`:
#   CONCERTINO_WORKTREE_BASE     dir (repo-relative) to hold worktrees
#   CONCERTINO_BASE_BRANCH       branch new worktree branches are cut from
#   CONCERTINO_FRONTEND_PORT_BASE / CONCERTINO_BACKEND_PORT_BASE   port bases
#   CONCERTINO_ENV_FILES         space-separated files to copy into the worktree
#   CONCERTINO_LINK_MODULES      space-separated module dirs (e.g.
#                                frontend/node_modules) to populate in the
#                                worktree so pre-commit hooks that need installed
#                                deps can run without `git commit -n`
#   CONCERTINO_WORKTREE_HOOKS    ;-separated commands to run inside the worktree
#   CONCERTINO_HARNESS           static harness default (empty when the project
#                                configures more than one harness — see below)
#   CONCERTINO_IMPLEMENTED_HARNESSES   space-separated set of harnesses with an
#                                implemented adapter (CON-62) — sourced from
#                                lib/config.js's VALID_HARNESSES at sync time;
#                                what HARNESS_OVERRIDE is validated against.
#
# CONCERTINO_BASE_REMOTE (default: origin) may be set in the environment.
#
# This script resolves TWO separate harness values (CON-62 design.md
# Decision 5 — deliberately kept apart, do not collapse them):
#
#   MODEL_TIER_HARNESS  the harness ACTUALLY running this process — the only
#                        value ever passed to resolve-speed.sh for per-role
#                        model-tier resolution. NEVER influenced by
#                        HARNESS_OVERRIDE. Resolution order:
#                          1. Runtime signal read directly from the process
#                             environment — CLAUDECODE set non-empty means
#                             claude-code; CODEX_SANDBOX or
#                             CODEX_SANDBOX_NETWORK_DISABLED set non-empty
#                             means codex; OPENCODE set non-empty means
#                             opencode (checked in that order, so CLAUDECODE
#                             wins if somehow more than one is set — CON-63).
#                          2. The static CONCERTINO_HARNESS default sourced
#                             from .concertino.env, when no runtime signal is
#                             present.
#                          3. The literal string "unknown", when neither
#                             resolves a value.
#
#   HARNESS              the identity/telemetry value — what run.start's
#                        `harness=` field and `READY harness=` report. Equal
#                        to MODEL_TIER_HARNESS UNLESS a valid
#                        HARNESS_OVERRIDE was passed, in which case the
#                        override wins here even if it contradicts the
#                        detected runtime signal (that contradiction never
#                        reaches MODEL_TIER_HARNESS — see above). Also
#                        printed as `READY harness_source=` naming which step
#                        produced it: ticket-override|runtime-detected|
#                        static-default|unknown.
#
# On success prints the stable READY contract (the orchestrator parses these):
#   READY worktree=<absolute path>
#   READY branch=<branch>
#   READY dev_port=<n>
#   READY backend_port=<n>
#   READY speed=<name>
#   READY budgets=<json>
#   READY models=<json>
#   READY second_final_gate_skeptic=<true|false>
#   READY evaluator_clean_worktree=<true|false>
#   READY harness=<value>
#   READY harness_source=ticket-override|runtime-detected|static-default|unknown
# Exits non-zero with "FAIL <reason>" on any error.
# ===========================================================================

TICKET_ID="${1:?usage: setup-worktree.sh <TICKET_ID> <BRANCH> [SPEED] [HARNESS_OVERRIDE]}"
BRANCH="${2:?usage: setup-worktree.sh <TICKET_ID> <BRANCH> [SPEED] [HARNESS_OVERRIDE]}"
SPEED="${3:-default}"
HARNESS_OVERRIDE="${4:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/git-child-env.sh"
# shellcheck disable=SC1091
[ -f "${SCRIPT_DIR}/.concertino.env" ] && source "${SCRIPT_DIR}/.concertino.env"

# Defense in depth (CON-62 design.md Decision 3): the orchestrator already
# validates a ticket-declared HARNESS_OVERRIDE before ever calling this
# script (before deriving a branch name, even), but this script is
# documented as the canonical entry point other tooling is meant to call
# directly rather than hand-roll worktree setup — so it independently
# re-validates any HARNESS_OVERRIDE it is given, before any git/worktree
# operation below, against the same CONCERTINO_IMPLEMENTED_HARNESSES source
# of truth (design.md Decision 4).
if [ -n "$HARNESS_OVERRIDE" ]; then
  _implemented_match=0
  for _h in ${CONCERTINO_IMPLEMENTED_HARNESSES:-}; do
    [ "$_h" = "$HARNESS_OVERRIDE" ] && { _implemented_match=1; break; }
  done
  if [ "$_implemented_match" -ne 1 ]; then
    echo "FAIL unsupported harness '${HARNESS_OVERRIDE}' — no adapter implemented (implemented: ${CONCERTINO_IMPLEMENTED_HARNESSES:-})" >&2
    exit 1
  fi
fi

# Detect the harness actually running this script from real, harness-set
# process environment variables — never a guess. None of these variables is
# a documented public contract, so only presence is relied on, not any
# particular value/format; the static CONCERTINO_HARNESS default and the
# literal "unknown" remain the fallback chain if detection ever stops
# working. See docs/config-reference.md for the full resolution order.
#
# OPENCODE: confirmed (not guessed) against the sst/opencode source —
# packages/opencode/src/index.ts's CLI entrypoint unconditionally sets
# `process.env.OPENCODE = "1"` before dispatching any subcommand, and the
# bash tool spawns child processes with the inherited environment, so this
# is present, non-empty, in any shell command an OpenCode agent runs.
# Checked last (lowest precedence) per design.md Decision 6.
detect_harness() {
  if [ -n "${CLAUDECODE:-}" ]; then echo "claude-code"; return; fi
  if [ -n "${CODEX_SANDBOX:-}" ] || [ -n "${CODEX_SANDBOX_NETWORK_DISABLED:-}" ]; then echo "codex"; return; fi
  if [ -n "${OPENCODE:-}" ]; then echo "opencode"; return; fi
  echo ""
}
RUNTIME_HARNESS="$(detect_harness)"
# NEVER influenced by HARNESS_OVERRIDE — see design.md Decision 5 / the
# module header comment above. This is the ONLY harness value passed to
# resolve-speed.sh below, so per-role model ids always stay valid for the
# harness actually executing the live Agent(...) calls in this process.
MODEL_TIER_HARNESS="${RUNTIME_HARNESS:-${CONCERTINO_HARNESS:-unknown}}"

# HARNESS / HARNESS_SOURCE — identity/telemetry only (run.start's `harness=`,
# READY harness=/harness_source=). A valid HARNESS_OVERRIDE wins here even
# when it contradicts RUNTIME_HARNESS; this is the literal "takes precedence
# ... over runtime env-based detection" CON-62's acceptance criteria ask for,
# scoped to identity, never to MODEL_TIER_HARNESS above.
if [ -n "$HARNESS_OVERRIDE" ]; then
  HARNESS="$HARNESS_OVERRIDE"
  HARNESS_SOURCE="ticket-override"
else
  HARNESS="$MODEL_TIER_HARNESS"
  HARNESS_SOURCE="${RUNTIME_HARNESS:+runtime-detected}"
  HARNESS_SOURCE="${HARNESS_SOURCE:-${CONCERTINO_HARNESS:+static-default}}"
  HARNESS_SOURCE="${HARNESS_SOURCE:-unknown}"
fi

# Resolve the speed against MODEL_TIER_HARNESS — passed explicitly rather
# than left for resolve-speed.sh to re-detect, so the two scripts'
# independent detection logic can never disagree with itself within one run
# (design.md Decision 3a). This is the run's ONE authoritative resolution:
# the orchestrator does not call resolve-speed.sh again itself, it just
# parses the READY lines this script prints below. MODEL_TIER_HARNESS, never
# HARNESS, is the one call site CON-62's HARNESS/MODEL_TIER_HARNESS split
# exists to protect (design.md Decision 5) — a contradicting
# HARNESS_OVERRIDE must never change which model ids get resolved here.
#
# `|| { ... }` (not a bare `$(...)` assignment) is deliberate: under
# `set -e`, `VAR=$(cmd)` DOES abort the script the instant cmd exits
# non-zero — verified directly — so the failure has to be caught in the same
# statement, not with a separate `$?` check afterward, which `-e` would
# never let this script reach.
RESOLVED_SPEED_JSON="$("${SCRIPT_DIR}/resolve-speed.sh" "$SPEED" "$MODEL_TIER_HARNESS" 2>&1)" || {
  echo "FAIL speed resolution failed for speed=${SPEED} harness=${MODEL_TIER_HARNESS}: ${RESOLVED_SPEED_JSON}" >&2
  exit 1
}
RESOLVED_BUDGETS_JSON="$(printf '%s' "$RESOLVED_SPEED_JSON" | jq -c '.budgets')"
RESOLVED_MODELS_JSON="$(printf '%s' "$RESOLVED_SPEED_JSON" | jq -c '.models')"
# CON-65: which provider this run's models resolved against — "ollama" or
# "default". resolve-speed.sh already folded CONCERTINO_PROVIDER (the
# per-window override the dashboard injects for a `provider:<value>` label)
# together with the project-level routing default, so this is the one
# truthful answer, not a re-derivation. `// "default"` keeps this script
# compatible with a pre-CON-65 rendered resolve-speed.sh that emits no
# .provider field at all.
RESOLVED_PROVIDER="$(printf '%s' "$RESOLVED_SPEED_JSON" | jq -r '.provider // "default"')"
# Not part of run.start (the spec's acceptance criterion only requires
# speed=/models= there — see delivery-speed-presets spec.md), but the
# orchestrator still needs both to populate workflow-state.md, and this
# script's own READY resolution is the run's ONE authoritative source for
# them (no second resolve-speed.sh invocation by the orchestrator itself —
# design.md Decision 3a) — so both travel through READY below.
RESOLVED_SECOND_FINAL_GATE_SKEPTIC="$(printf '%s' "$RESOLVED_SPEED_JSON" | jq -r '.secondFinalGateSkeptic')"
RESOLVED_EVALUATOR_CLEAN_WORKTREE="$(printf '%s' "$RESOLVED_SPEED_JSON" | jq -r '.evaluatorCleanWorktree')"

# CON-191: instrumentation digest, computed over the RENDERED
# scripts/concertino/**/*.sh files in the repository being operated on —
# never over core/'s own templates, since a locally patched rendered copy
# (the CON-128 case) is precisely what this exists to detect (design.md
# Decision 3). SCRIPT_DIR is this script's own directory, i.e. the rendered
# scripts/concertino/ this process is itself running from.
#
# CON-191 skeptic-final-1 (round 1, REFUTE): this originally walked
# SCRIPT_DIR non-recursively (top-level `.sh` files only), silently
# excluding everything under `scripts/concertino/lib/` — including
# `lib/auditor-lease.sh`, which THIS SCRIPT'S OWN SIBLING emit-event.sh
# `source`s on every invocation, so its content is directly part of what
# executes. A patch to a nested `lib/*.sh` file moved the digest not at all
# — the exact CON-128 shape this exists to catch. Fixed by walking
# recursively and keying/sorting on the full, forward-slash-normalized
# RELATIVE path (e.g. `lib/auditor-lease.sh`), never a bare basename, which
# could collide across directories or sort inconsistently. Kept in lockstep
# with lib/cli/emit.js's computeInstrumentationManifest(), which the
# render-time baseline this compares against is written by.
#
# Deliberately non-fatal end to end (design.md's "computing the digest SHALL
# NOT fail a run" / task 3.2): every step below degrades to an empty
# manifest rather than aborting under `set -e`, and run.start is emitted
# with or without the digest field depending only on whether this succeeded.
compute_instrumentation_manifest() {
  node -e '
    const fs = require("fs"), path = require("path"), crypto = require("crypto");
    // Mirrors lib/cli/shared.js'"'"'s listFilesRecursive(): forward-slash-
    // joined relative paths, sorted, regardless of platform.
    function listShFilesRecursive(dir, prefix) {
      let out = [];
      let entries;
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch (e) {
        return out;
      }
      for (const entry of entries) {
        const abs = path.join(dir, entry.name);
        const rel = prefix ? prefix + "/" + entry.name : entry.name;
        if (entry.isDirectory()) {
          out = out.concat(listShFilesRecursive(abs, rel));
        } else if (entry.isFile() && entry.name.endsWith(".sh")) {
          out.push(rel);
        }
      }
      return out;
    }
    try {
      const dir = process.argv[1];
      const files = listShFilesRecursive(dir, "").sort();
      const fileHashes = {};
      const agg = crypto.createHash("sha256");
      for (const f of files) {
        const content = fs.readFileSync(path.join(dir, f));
        const h = crypto.createHash("sha256").update(content).digest("hex");
        fileHashes[f] = h;
        agg.update(f + ":" + h + "\n");
      }
      process.stdout.write(JSON.stringify({ digest: agg.digest("hex"), files: fileHashes }));
    } catch (e) {
      process.exit(1);
    }
  ' "$1"
}

INSTRUMENTATION_MANIFEST="$(compute_instrumentation_manifest "$SCRIPT_DIR" 2>/dev/null)" || INSTRUMENTATION_MANIFEST=""
INSTRUMENTATION_DIGEST=""
if [ -n "$INSTRUMENTATION_MANIFEST" ]; then
  INSTRUMENTATION_DIGEST="$(printf '%s' "$INSTRUMENTATION_MANIFEST" | node -e '
    let s = "";
    process.stdin.on("data", (d) => { s += d; });
    process.stdin.on("end", () => {
      try { process.stdout.write(JSON.parse(s).digest || ""); } catch (e) { /* leave empty */ }
    });
  ' 2>/dev/null)" || INSTRUMENTATION_DIGEST=""
fi

REPO_ROOT="$(git_child rev-parse --show-toplevel)"
cd "$REPO_ROOT"

WORKTREE_BASE="${CONCERTINO_WORKTREE_BASE:-.concertino/worktrees}"
FRONTEND_PORT_BASE="${CONCERTINO_FRONTEND_PORT_BASE:-5173}"
BACKEND_PORT_BASE="${CONCERTINO_BACKEND_PORT_BASE:-8080}"
BASE_REMOTE="${CONCERTINO_BASE_REMOTE:-origin}"
BASE_BRANCH="${CONCERTINO_BASE_BRANCH:-main}"

# Derive stable ports from the ticket number PLUS a small deterministic hash
# of the team prefix (CON-67) so parallel orchestrators never collide — even
# across teams: same-numbered tickets from different teams (CON-55 vs HEL-55)
# used to resolve to identical ports.
#
# KEEP IN LOCKSTEP with derivePorts() in lib/ui/screens/launchplan.js — the
# launch plan's pre-flight port preview deliberately duplicates this exact
# arithmetic, and its own comment points back here.
#
# Hash: over the team prefix (everything before the LAST '-'; empty when the
# id has no '-'), h = (h*31 + charcode) % 1000 per character, then
# TEAM_OFFSET = (h % 8) * 37 — bounded to 0..259, so with sane bases the
# final ports stay non-privileged and well under 65535. Pure arithmetic on
# the ticket id, so reruns of a ticket always reuse its ports.
# e.g. CON-55 with default bases -> dev 5302, backend 8209; HEL-55 -> 5487, 8394.
TICKET_NUM="${TICKET_ID##*-}"
if ! [[ "$TICKET_NUM" =~ ^[0-9]+$ ]]; then
  echo "FAIL could not derive numeric ticket id from '$TICKET_ID'" >&2
  exit 1
fi
TEAM_PREFIX=""
case "$TICKET_ID" in *-*) TEAM_PREFIX="${TICKET_ID%-*}" ;; esac
TEAM_HASH=0
for (( _i = 0; _i < ${#TEAM_PREFIX}; _i++ )); do
  TEAM_HASH=$(( (TEAM_HASH * 31 + $(printf '%d' "'${TEAM_PREFIX:$_i:1}")) % 1000 ))
done
TEAM_OFFSET=$(( (TEAM_HASH % 8) * 37 ))
DEV_PORT=$((FRONTEND_PORT_BASE + TEAM_OFFSET + TICKET_NUM))
BACKEND_PORT=$((BACKEND_PORT_BASE + TEAM_OFFSET + TICKET_NUM))

WORKTREE_PATH="${REPO_ROOT}/${WORKTREE_BASE}/${BRANCH}"

# Create the worktree (reuse if it already exists for this branch).
if git_child worktree list --porcelain | grep -qx "worktree ${WORKTREE_PATH}"; then
  echo "note: worktree already present, reusing ${WORKTREE_PATH}" >&2
elif git_child show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git_child worktree add "$WORKTREE_PATH" "$BRANCH"      # branch exists, attach
else
  # New branch: cut from the fetched remote base, never from whatever local HEAD
  # happens to be. In a burst of sequential tickets each PR squash-merges on the
  # remote while local <base> stays behind, so branching from HEAD silently
  # produces conflicts whenever two tickets touch the same file.
  # Resuming an existing branch (above) must never re-base — only this path syncs.
  if git_child fetch --quiet "$BASE_REMOTE" "$BASE_BRANCH" 2>/dev/null &&
    git_child show-ref --verify --quiet "refs/remotes/${BASE_REMOTE}/${BASE_BRANCH}"; then
    BASE_REF="${BASE_REMOTE}/${BASE_BRANCH}"
  elif git_child show-ref --verify --quiet "refs/heads/${BASE_BRANCH}"; then
    BASE_REF="$BASE_BRANCH"
    echo "note: could not fetch ${BASE_REMOTE}/${BASE_BRANCH} — cutting from local ${BASE_BRANCH}" >&2
  else
    BASE_REF="HEAD"
    echo "note: no ${BASE_BRANCH} ref found — cutting from HEAD" >&2
  fi
  # --no-track: branching off a remote ref would otherwise set upstream to
  # <remote>/<base>, so `git status` reports the new branch as "ahead of main"
  # and a stray `git pull` would merge base in. Delivery sets the real upstream
  # with `git push -u origin <branch>`.
  git_child worktree add --no-track "$WORKTREE_PATH" -b "$BRANCH" "$BASE_REF"
fi

# Copy env/secret files the app needs at boot but that aren't committed. Without
# these the dev server (and any login) fails. This is the step prose leaves implicit.
for f in ${CONCERTINO_ENV_FILES:-}; do
  if [ -f "${REPO_ROOT}/${f}" ]; then
    mkdir -p "$(dirname "${WORKTREE_PATH}/${f}")"
    cp -n "${REPO_ROOT}/${f}" "${WORKTREE_PATH}/${f}" 2>/dev/null || true
  else
    echo "note: ${REPO_ROOT}/${f} not found — app may need env set another way" >&2
  fi
done

# Populate configured module directories (e.g. frontend/node_modules) so the
# worktree can run the full pre-commit hook chain — Husky's frontend lint/test
# step needs installed deps, and without this every backend-only ticket resorts
# to `git commit -n`. Runs BEFORE the hooks loop so `npx husky install` (and any
# other hook) sees populated modules.
#
# Best-effort: this script runs under `set -euo pipefail`, so every fallible
# command below (`cmp -s`, `cp -al`, `npm ci`) is guarded to degrade to a
# `note:` and continue — setup MUST still reach the READY lines.
#
# Per module dir M (parent P = dirname M, lockfile P/package-lock.json): prefer a
# HARDLINK COPY (`cp -al`) of the main checkout's modules — near-instant, shared
# inodes, near-zero disk — but the worktree's copy is an independent directory
# entry, so a later `npm ci`/`rm -rf` in the worktree cannot corrupt the main
# checkout. A symlink into the main checkout is intentionally NOT used: `npm ci`
# in the worktree would recurse the link and wipe the shared main modules. Fall
# back to `npm ci` when the lockfile differs, the main modules are missing, or
# the hardlink copy fails (e.g. EXDEV — worktree on a different filesystem).
for M in ${CONCERTINO_LINK_MODULES:-}; do
  [ -z "$M" ] && continue
  P="$(dirname "$M")"
  MAIN_M="${REPO_ROOT}/${M}"
  WT_M="${WORKTREE_PATH}/${M}"
  MAIN_LOCK="${REPO_ROOT}/${P}/package-lock.json"
  WT_LOCK="${WORKTREE_PATH}/${P}/package-lock.json"

  # Idempotent: skip if the worktree already has it (real dir or existing link).
  if [ -e "$WT_M" ] || [ -L "$WT_M" ]; then
    echo "note: ${M} already present in worktree — skipping populate" >&2
    continue
  fi

  did_hardlink=0
  if [ -d "$MAIN_M" ] && [ -f "$MAIN_LOCK" ] && [ -f "$WT_LOCK" ] && cmp -s "$MAIN_LOCK" "$WT_LOCK"; then
    # Unchanged deps → hardlink copy of the main modules.
    if cp -al "$MAIN_M" "$WT_M" 2>/dev/null; then
      did_hardlink=1
    else
      echo "note: hardlink copy of ${M} failed (cross-filesystem?) — falling back to npm ci" >&2
    fi
  fi

  if [ "$did_hardlink" -eq 0 ]; then
    # Lockfile drift, missing/absent main modules, or a failed hardlink copy →
    # real install so the worktree gets its own correct modules.
    if [ -f "$WT_LOCK" ]; then
      ( cd "${WORKTREE_PATH}/${P}" && npm ci >/dev/null 2>&1 ) \
        || echo "note: 'npm ci' for ${M} failed — worktree may need a manual install" >&2
    else
      echo "note: no ${P}/package-lock.json and no reusable main ${M} — leaving ${M} unpopulated" >&2
    fi
  fi
done

# Run project-defined worktree hooks (e.g. `npx husky install`, `npm ci`).
if [ -n "${CONCERTINO_WORKTREE_HOOKS:-}" ]; then
  IFS=';' read -ra HOOKS <<< "$CONCERTINO_WORKTREE_HOOKS"
  for hook in "${HOOKS[@]}"; do
    hook="$(echo "$hook" | sed 's/^ *//;s/ *$//')"
    [ -z "$hook" ] && continue
    # Strip GIT_* before eval'ing the configured hook (not just for the
    # literal `npx husky install` default): any hook configured here may
    # write into .git, and a hook run under an inherited poisoned GIT_DIR
    # would misdirect onto the wrong repository regardless of `cd
    # $WORKTREE_PATH`. Protects every hook this var may ever be set to, not
    # only the currently configured one. See core/scripts/lib/git-child-env.sh.
    ( cd "$WORKTREE_PATH" || exit 0; unset -v $(compgen -v GIT_ 2>/dev/null) 2>/dev/null; eval "$hook" >/dev/null 2>&1 ) || true
  done
fi

# Tier-2 telemetry: the dashboard's run header, emitted by the script rather
# than the agent so a run can never appear without a truthful identity.
# `speed=`/`models=` fold the resolve-speed.sh output computed above into
# this same event, so a run's rigour is recorded truthfully alongside its
# identity in the one place the dashboard already renders as the run's
# header (design.md Decision 3a) — `models=` is the compact per-role JSON
# object; emit-event.sh already handles arbitrary key=value fields, JSON
# value included (see its own `context=` handling for escalations).
RUN_START_ARGS=(
  "ticket=${TICKET_ID}"
  "branch=${BRANCH}"
  "worktree=${WORKTREE_PATH}"
  "dev_port=${DEV_PORT}"
  "backend_port=${BACKEND_PORT}"
  "harness=${HARNESS}"
  "speed=${SPEED}"
  "provider=${RESOLVED_PROVIDER}"
  "models=${RESOLVED_MODELS_JSON}"
)
# CON-191 task 3.1/3.2: only added when it could actually be computed — a
# digest that could not be computed for any reason must never fail run.start
# or setup itself (design.md's graceful-degradation requirement).
[ -n "$INSTRUMENTATION_DIGEST" ] && RUN_START_ARGS+=("instrumentation_digest=${INSTRUMENTATION_DIGEST}")

CONCERTINO_ROLE=script "${SCRIPT_DIR}/emit-event.sh" run.start "${RUN_START_ARGS[@]}" || true

# CON-191 task 3.3–3.6: compare the live digest just computed against the
# render-time baseline `concertino sync` wrote alongside these scripts
# (design.md Decision 4). No baseline (a repo that has not re-synced since
# this change — helio's state until the batch is synced, by owner ruling) is
# NOT drift: the live digest is still recorded above, nothing more happens
# here, and the run proceeds. This block is best-effort in the same way the
# digest computation itself is — a comparison failure must never fail setup.
INSTRUMENTATION_BASELINE_FILE="${SCRIPT_DIR}/.instrumentation-manifest.json"
if [ -n "$INSTRUMENTATION_MANIFEST" ] && [ -f "$INSTRUMENTATION_BASELINE_FILE" ]; then
  AFFECTED_SCRIPTS="$(node -e '
    try {
      const fs = require("fs");
      const baseline = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      const live = JSON.parse(process.argv[2]);
      const baseFiles = baseline.files || {};
      const liveFiles = live.files || {};
      const names = new Set([...Object.keys(baseFiles), ...Object.keys(liveFiles)]);
      const diffs = [...names].filter((n) => baseFiles[n] !== liveFiles[n]).sort();
      process.stdout.write(diffs.join(","));
    } catch (e) {
      process.exit(1);
    }
  ' "$INSTRUMENTATION_BASELINE_FILE" "$INSTRUMENTATION_MANIFEST" 2>/dev/null)" || AFFECTED_SCRIPTS=""
  if [ -n "$AFFECTED_SCRIPTS" ]; then
    CONCERTINO_ROLE=script "${SCRIPT_DIR}/emit-event.sh" schema.change \
      "ticket=${TICKET_ID}" \
      "reason=rendered-script-drift" \
      "affected_scripts=${AFFECTED_SCRIPTS}" || true
  fi
fi

echo "READY worktree=${WORKTREE_PATH}"
echo "READY branch=${BRANCH}"
echo "READY dev_port=${DEV_PORT}"
echo "READY backend_port=${BACKEND_PORT}"
echo "READY speed=${SPEED}"
echo "READY budgets=${RESOLVED_BUDGETS_JSON}"
echo "READY models=${RESOLVED_MODELS_JSON}"
echo "READY second_final_gate_skeptic=${RESOLVED_SECOND_FINAL_GATE_SKEPTIC}"
echo "READY evaluator_clean_worktree=${RESOLVED_EVALUATOR_CLEAN_WORKTREE}"
echo "READY harness=${HARNESS}"
echo "READY provider=${RESOLVED_PROVIDER}"
echo "READY harness_source=${HARNESS_SOURCE}"
