package com.helio.domain.engine

import spray.json._

/** HEL-599 design.md D1 — the single traversal both schema inference and row materialisation
 *  must derive from. Before this existed, `SchemaInferenceEngine.flattenObject` recursed into
 *  nested `JsObject`s while `PipelineRowJson.jsRowToRow` mapped only one level, so a DataType
 *  could advertise a dotted column (`stats.pts_ppr`) that the materialised row never carried.
 *  Duplicating the traversal a second time (rather than extracting it) would only restore
 *  agreement today and let it drift again tomorrow -- so both call sites project the same
 *  `leaves` enumeration through their own, unrelated value-conversion logic
 *  (`SchemaInferenceEngine.inferJsonType` / `PipelineRowJson.jsValueToAny`). `JsonFlattener`
 *  itself knows nothing about types or engine row values -- structure only.
 *
 *  Contract:
 *   - Object values recurse; every other `JsValue` (including `JsArray`) is a leaf at its own
 *     dotted path (design D2). Array-of-scalars and array-of-objects are treated identically --
 *     index expansion is rejected because a row's array length would make the column set
 *     depend on that row's data, reproducing the same ordering-dependent-schema failure HEL-858
 *     exists to fix on the merge side.
 *   - Traversal is bounded by `MaxDepth`. An object encountered AT the bound is treated as a
 *     leaf (its compact JSON text, same as an array) rather than raising or silently dropping
 *     the column -- degrade, don't fail (design D3).
 *   - The returned `Seq` contains AT MOST ONE pair per dotted path -- deduplicated inside `leaves`
 *     itself, not left for each caller to fold into a `Map` on its own. A duplicate-path collision
 *     (`{"a.b": 1, "a": {"b": 2}}`) resolves deterministically to "last-in-original-walk-order
 *     wins" (design D4). Deduplicating here (rather than trusting every projection to fold pairs
 *     into a `Map`) is what makes "exactly one `a.b` column" true on BOTH projections, including
 *     `SchemaInferenceEngine.flattenObject`'s `InferredField` sequence -- which, unlike a row, is
 *     never folded into a `Map` by its own consumer. Final-gate skeptic round 1 found exactly
 *     this: a caller-side-only fold left a duplicate-named field in the schema while the row
 *     deduplicated, silently breaking the "schema and rows never disagree" guarantee on its own
 *     collision edge case. The returned `Seq` is additionally sorted by path for a stable,
 *     readable order (a global path sort, not the previous per-level `sortBy`
 *     `SchemaInferenceEngine.flattenObject` used before this ticket).
 *   - Purely per-object: no cross-row merge policy lives here. HEL-858 replaced the old
 *     `SchemaInferenceEngine.mergeObjects` (which merged raw objects at the top level, before
 *     flattening, first-non-null-wins) with `SchemaInferenceEngine.inferFromObjects`, a
 *     union/widen over the leaf *paths* this traversal produces -- without needing any change to
 *     this traversal itself, exactly as anticipated below.
 */
object JsonFlattener {

  /** Depth beyond which a nested object is treated as a leaf rather than recursed into.
   *  Far beyond any real API shape (the Sleeper payload driving this ticket nests 3 deep) while
   *  still finite, so a pathological or cyclic-looking response cannot grow the column set
   *  without bound. */
  val MaxDepth: Int = 10

  /** Enumerate `obj`'s leaves as `(dotted path, leaf JsValue)` pairs -- at most one pair per
   *  path, sorted by path. */
  def leaves(obj: JsObject): Seq[(String, JsValue)] = {
    // `walk` can emit the same dotted path more than once on pathological input (a literal
    // dotted key colliding with a path generated by nesting). Fold to a `Map` first (last
    // pair in `walk`'s own emission order wins, deterministically -- design D4) so every
    // consumer -- including `SchemaInferenceEngine.flattenObject`, which builds an
    // `InferredField` `Seq` directly from this and never folds it into a `Map` itself -- sees
    // exactly one entry per path. Then re-sort for a stable, readable order.
    val deduped = walk(obj, prefix = "", depth = 0).foldLeft(scala.collection.immutable.ListMap.empty[String, JsValue]) {
      case (acc, (path, value)) => acc.updated(path, value)
    }
    deduped.toSeq.sortBy(_._1)
  }

  /** Leaves re-assembled into a flat `JsObject` -- the shape `SourceService.previewRest` needs
   *  so preview, the advertised schema, and the executed rows all agree (design D6). */
  def flattenJsObject(obj: JsObject): JsObject =
    JsObject(leaves(obj).toMap)

  private def walk(obj: JsObject, prefix: String, depth: Int): Seq[(String, JsValue)] =
    obj.fields.toSeq.flatMap { case (key, value) =>
      val fullKey = if (prefix.isEmpty) key else s"$prefix.$key"
      value match {
        case nested: JsObject if depth < MaxDepth - 1 =>
          walk(nested, fullKey, depth + 1)
        case _ =>
          // Non-object, OR an object encountered at the depth bound: both are leaves.
          Seq(fullKey -> value)
      }
    }
}
